src/Entity/ComposerJson.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Enum\ProjectType;

/**
 * Class ComposerJson
 *
 * @author Joachim Beig
 */
class ComposerJson
{
    public const FILE_NAME = 'composer.json';

    private array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function getData(): array
    {
        return $this->data;
    }

    public function getName(): ?string
    {
        return $this->data['name'] ?? null;
    }

    public function getType(): ?ProjectType
    {
        if (!isset($this->data['type'])) {
            return null;
        }
        if (!ProjectType::isValid($this->data['type'])) {
            return null;
        }
        return new ProjectType($this->data['type']);
    }

    public function getRequire(): array
    {
        return $this->data['require'] ?? [];
    }

    public function getRequireDev(): array
    {
        return $this->data['require-dev'] ?? [];
    }

    public function getAllRequired(): array
    {
        return array_merge($this->getRequire(), $this->getRequireDev());
    }

    public static function fromFile(string $file): ComposerJson
    {
        if (is_file($file) === true) {
            return new ComposerJson(json_decode(file_get_contents($file), true));
        }

        return new ComposerJson([]);
    }
}

src/Entity/Enum/ProjectType.php
<?php

declare(strict_types=1);

namespace App\Entity\Enum;

use MyCLabs\Enum\Enum;

/**
 * Class ProjectType
 *
 * @author Joachim Beig
 *
 * @method static ProjectType PROJECT()
 * @method static ProjectType LIBRARY()
 * @method static ProjectType METAPACKAGE()
 * @method static ProjectType COMPOSER_PLUGIN()
 *
 */
class ProjectType extends Enum
{
    public const PROJECT = 'project';
    public const LIBRARY = 'library';
    public const METAPACKAGE = 'metapackage';
    public const COMPOSER_PLUGIN = 'composer-plugin';
}

src/Entity/Project.php
<?php

namespace App\Entity;

use App\Entity\Enum\ProjectState;
use App\Repository\ProjectRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(indexes={@ORM\Index(columns={"name"})})
 */
class Project
{
    /**
     * @var string|null
     * @ORM\Id()
     * @ORM\Column(type="string",  length=36, unique=true)
     */
    private ?string $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $name;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private string $source;

    /**
     * @ORM\Column(type=ProjectState::class, length=50)
     */
    private ProjectState $projectState;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private string $latestVersion;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private DateTimeInterface $latestVersionTime;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private bool $abandoned;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $abandonedRecommendation;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $modified = null;

    private ?ComposerJson $composerJson;

    private ?ComposerLock $composerLock;

    public function __construct(
        string $name,
        string $source,
        ProjectState $projectState
    ) {
        $this->name = $name;
        $this->source = $source;
        $this->projectState = $projectState;
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getSource(): string
    {
        return $this->source;
    }

    public function setSource(string $source): void
    {
        $this->source = $source;
    }

    public function getProjectState(): ?ProjectState
    {
        return $this->projectState;
    }

    public function setProjectState(ProjectState $projectState): void
    {
        $this->projectState = $projectState;
    }

    public function getLatestVersion(): string
    {
        return $this->latestVersion;
    }

    public function setLatestVersion(string $latestVersion): void
    {
        $this->latestVersion = $latestVersion;
    }

    public function getLatestVersionTime(): DateTimeInterface
    {
        return $this->latestVersionTime;
    }

    public function setLatestVersionTime(DateTimeInterface $latestVersionTime): void
    {
        $this->latestVersionTime = $latestVersionTime;
    }

    public function isAbandoned(): bool
    {
        return $this->abandoned;
    }

    public function setAbandoned(bool $abandoned): void
    {
        $this->abandoned = $abandoned;
    }

    public function getAbandonedRecommendation(): ?string
    {
        return $this->abandonedRecommendation;
    }

    public function setAbandonedRecommendation(?string $abandonedRecommendation): void
    {
        $this->abandonedRecommendation = $abandonedRecommendation;
    }

    public function getModified(): ?DateTimeInterface
    {
        return $this->modified;
    }

    public function setModified(DateTimeInterface $modified): void
    {
        $this->modified = $modified;
    }

    public function getComposerJson(): ?ComposerJson
    {
        return $this->composerJson;
    }

    public function setComposerJson(?ComposerJson $composerJson): void
    {
        $this->composerJson = $composerJson;
    }

    public function getComposerLock(): ?ComposerLock
    {
        return $this->composerLock;
    }

    public function setComposerLock(?ComposerLock $composerLock): void
    {
        $this->composerLock = $composerLock;
    }

    /**
     * @ORM\PrePersist()
     */
    public function createId(): void
    {
        $this->id = Uuid::uuid4()->toString();
    }

    /**
     * @ORM\PrePersist()
     */
    public function updateModified(): void
    {
        $this->modified = new DateTime();
    }
}

src/Controller/ProjectController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Enum\ProjectState;
use App\Entity\Project;
use App\Entity\ProjectDependency;
use App\Repository\ProjectDependencyRepository;
use App\Repository\ProjectRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProjectController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/project/{projectId}", name="app_project_details")
     * @param string $projectId
     * @return Response
     */
    public function project(string $projectId): Response
    {
        /** @var ProjectRepository $projectRepository */
        $projectRepository = $this->entityManager->getRepository(Project::class);

        // TODO: Put this into parent controller
        $directProjects = $projectRepository->findByState(ProjectState::DIRECT());

        /** @var ProjectDependencyRepository $projectDependencyRepository */
        $projectDependencyRepository = $this->entityManager->getRepository(ProjectDependency::class);

        $project = $projectRepository->find($projectId);

        $dependencies = $projectDependencyRepository->findBy(['projectScope' => $project->getId()]);

        // Load all required projects
        $requiredProjects = [];
        $requirements = [];
        foreach ($dependencies as $dependency) {
            if (isset($requiredProjects[$dependency->getProject()]) === false) {
                $requiredProjects[$dependency->getProject()] = $projectRepository->find($dependency->getProject());
            }
            if (isset($requiredProjects[$dependency->getRequires()]) === false) {
                $requiredProjects[$dependency->getRequires()] = $projectRepository->find($dependency->getRequires());
            }

            $dependencyProject = $requiredProjects[$dependency->getProject()];
            $dependencyRequires = $requiredProjects[$dependency->getRequires()];

            if (isset($requirements[$dependencyRequires->getName()]) === false) {
                $requirements[$dependencyRequires->getName()] = [
                    'project' => $dependencyRequires->getName(),
                    'installed_version' => $dependency->getInstalledVersion(),
                    'required_by' => []
                ];
            }

            $requirements[$dependencyRequires->getName()]['required_by'][] = $dependencyProject->getName() . ' => '
                . $dependency->getRequiredVersion();

        }

        ksort($requirements);

        $dependantProjects = [];

        $dependants = $projectDependencyRepository->findBy(['requires' => $project->getId()]);

        return $this->render(
            'project/project.html.twig',
            compact('directProjects', 'project', 'dependencies', 'requiredProjects', 'requirements', 'dependants')
        );
    }

}

templates/project/project.html.twig
{% extends 'page.html.twig' %}

{% block body %}
    <main class="pt-5 px-lg-5">
        <h1 class="pt-5">{{ project.name }}</h1>

        <section id="details">
            <dl class="row">
                <dt class="col-sm-3">Source</dt>
                <dd class="col-sm-9">{{ project.source }}</dd>

                <dt class="col-sm-3">Latest Version</dt>
                <dd class="col-sm-9">{{ project.latestVersion }}</dd>

                <dt class="col-sm-3">Latest Version Time</dt>
                <dd class="col-sm-9">{{ project.latestVersionTime|date('Y-m-d H:i:s') }}</dd>
            </dl>
        </section>

        <section id="requirements">
            <h2 class="pt-5">Requirements</h2>
            <table class="table table-bordered table-striped">
                <thead>
                    <tr class="table-primary">
                        <th>Project</th>
                        <th>Installed Version</th>
                        <th>Required By</th>
                    </tr>
                </thead>
                <tbody>
                {% for requirement in requirements %}
                    <tr>
                        <td style="white-space: nowrap;"><a href="{{ path('app_project_details', {projectId: "todo"}) }}">{{ requirement.project }}</a></td>
                        <td style="white-space: nowrap;">{{ requirement.installed_version }}</td>
                        <td style="white-space: nowrap;">{% for required_by in requirement.required_by %}<a href="{{ path('app_project_details', {projectId: "todo"}) }}">{{ required_by }}</a><br>{% endfor %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if requirements|length == 0 %}
                <div class="alert alert-info text-center">No requirements found</div>
            {% endif %}
        </section>

        <section id="dependents">
            <h2 class="pt-5">Dependents</h2>
            <table class="table table-bordered table-striped">
                <thead>
                    <tr class="table-primary">
                        <th>Project</th>
                        <th>Required Version</th>
                        <th>Require DEV</th>
                        <th>Installed Version</th>
                    </tr>
                </thead>
                <tbody>
                {% for dependant in dependants %}
                    <tr>
                        <td style="white-space: nowrap"><a href="{{ path('app_project_details', {projectId: dependant.project}) }}">{{ dependant.project }}</a></td>
                        <td style="white-space: nowrap">{{ dependant.requiredVersion }}</td>
                        <td style="white-space: nowrap">{{ dependant.requireDev ? 'yes' : 'no' }}</td>
                        <td style="white-space: nowrap"><a href="{{ path('app_project_details', {projectId: "todo"}) }}">{{ dependant.installedVersion }}</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if dependants|length == 0 %}
                <div class="alert alert-info text-center">No dependants found</div>
            {% endif %}
        </section>

    </main>
{% endblock %}